springdoc:
  use-management-port: true

server:
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui
---
spring:
  config:
    activate:
      on-profile: dev
products:
  prefix: "[sample] "
